[package]
name = "levenshtein_automaton"
version = "0.1.0"
authors = ["Paul Masurel <paul.masurel@gmail.com>"]

[dependencies]
fst = {version="0.3", optional=true}

[dev-dependencies]
levenshtein = "1.0"

[features]
fst_automaton = ["fst"]